name: Java CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v13.0.0
      with:
        java-version: 13.0.0
    - name: Build with Maven
      run: mvn -B package --file pom.xml
